# Banco do Nordeste

structure:
  - HEADER
  -
    - TRANSACTION
  - TRAILER

registries:
  HEADER:
    pattern: /^02RETORNO(\d{2}).{15}(\d{4})(\d{2})(\d{7})(\d) {6}(.{30})(004)(.{15})(\d{6}).{8}(\d{5}) {6}(\d{6}) {269}(\d{6})$/
    map:
      - service_code
      - assignor_agency
      - assignor_agency_cd
      - assignor_account
      - assignor_account_cd
      - assignor_name
      - bank_code
      - bank_name
      - record_date
      - file_sequence
      - credit_date
      - registry

  TRANSACTION:
    pattern: /^1(\d{2})(\d{14})(\d{4})(\d{2})(\d{7})(\d) {6}(.{25})(\d{8})(\d{10}) {27}(\d)(\d{2})(\d{6})(.{10})(\d{8}) {12}(\d{6})(\d{13})(\d{3})(\d{4}) (\d{2})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(.{115})(\d{6})$/
    map:
      - assignor_document_type
      - assignor_document
      - assignor_agency
      - assignor_agency_cd
      - assignor_account
      - assignor_account_cd
      - doc_number
      - our_number
      - contract
      - wallet
      - occurrence
      - occurrence_date
      - your_number
      - confirm_our_number
      - due
      - value
      - receiver_bank
      - receiver_agency
      - kind
      - tax
      - expenses
      - interest
      - ioc_iof
      - rebate
      - discount_value
      - value_received
      - interest_value
      - error_table
      - registry

  TRAILER:
    pattern: /^92(\d{2})(004) {10}(\d{8})(\d{14})(\d{8}) {347}(\d{6})$/
    map:
      - service_code
      - bank_code
      - title_cs_count
      - title_cs_total
      - warning_cs
      - registry
