# Banese

structure:
  - HEADER
  -
    - TRANSACTION
  - TRAILER

registries:
  HEADER:
    pattern: /^02RETORNO(\d{2}).{15}\d{8}(\d{3})(\d{8})(\d)(.{30})(047)(.{15})(\d{6})(\d{2})(\d{14}) {273}(\d{5})(\d{6})$/
    map:
      - service_code
      - assignment_agency
      - assignment_account
      - assignment_account_cd
      - assignor_name
      - bank_code
      - bank_name
      - record_date
      - assignor_document_type
      - assignor_document
      - file_sequence
      - registry

  TRANSACTION:
    pattern: /^1(\d{2})(\d{14})\d{8}(\d{3})(\d{8})(\d)(.{25})(\d{19})(\d) {25}(\d)(\d{2})(\d{6})(.{10}) {20}(\d{6})(\d{13})(.{3})(\d{5})(\d{2})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13}) {9}(.)(\d{12})(\d{6})(\d{13})(\d{2})(\d{2}) {54}(\d{2})(\d)(\d{6})$/
    map:
      - assignor_document_type
      - assignor_document
      - assignment_agency
      - assignment_account
      - assignment_account_cd
      - assignor_use
      - our_number
      - our_number_cd
      - wallet
      - occurrence
      - occurrence_date
      - doc_number
      - due
      - value
      - receiver_bank
      - receiver_agency
      - kind
      - tax
      - expenses
      - interest_discount
      - ioc_iof
      - rebate
      - discount_value
      - value_received
      - interest_value
      - credits
      - confirm_interest
      - confirm_interest_charge
      - confirm_discount
      - confirm_discount_value
      - confirm_instruction1
      - confirm_instruction2
      - confirm_protest
      - currency
      - registry

  TRAILER:
    pattern: /^92(\d{2})(047) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{14})(\d{3})(\d{14})(\d{14})(\d{14})(\d{14}) {144}(\d{6})$/
    map:
      - service_code
      - bank_code
      - title_cs_count
      - title_cs_total
      - warning_cs
      - title_cv_count
      - title_cv_total
      - warning_cv
      - title_cc_count
      - title_cc_total
      - warning_cc
      - title_cd_count
      - title_cd_total
      - warning_cd
      - discount_margin
      - down_rate
      - regular_titles
      - loan_limit
      - loan_balance
      - loan_fine
      - registry
