CNAB240:
  registry_length: 240

  structure:
    - unique: FILE_HEADER
    - multiple:
      - unique: LOT_HEADER
      - multiple: TITLE_T TITLE_U
      - unique: LOT_TRAILER
    - unique: FILE_TRAILER

  registries:
    FILE_HEADER:
      pattern: /^(.{3})(\d{4})0 {9}(\d{1})(\d{14})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{30}) {10}2(\d{8})(\d{6})(\d{6})(\d{3})(\d{5}) {20}( {20}) {29}$/
      map:
        - bank_code
        - lot
        - assignor_document_type
        - assignor_document
        - assignor_covenant
        - assignor_agency
        - assignor_agency_cd
        - assignor_account
        - assignor_account_cd
        - assignor_agency_account_cd
        - assignor_name
        - bank_name
        - record_date
        - record_time
        - file_sequence
        - file_layout
        - density
        - assignor_use

    LOT_HEADER:
      pattern: /^(.{3})(\d{4})1([RT])(\d{2}) {2}(\d{3}) (\d{1})(\d{15})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{40})(.{40})(\d{8})(\d{8})(\d{8}) {33}$/
      map:
        - bank_code
        - lot
        - service_code
        - service_type
        - lot_layout
        - assignor_document_type
        - assignor_document
        - assignor_covenant
        - assignor_agency
        - assignor_agency_cd
        - assignor_account
        - assignor_account_cd
        - assignor_agency_account_cd
        - assignor_name
        - message1
        - message2
        - shipping_return_number
        - shipping_return_record_date
        - credit_date

    TITLE_T:
      pattern: /^(.{3})(\d{4})3(\d{5})T (\d{2})(\d{5})(.)(\d{12})(.)(.)(\d{20})(\d)(.{15})(\d{8})(\d{15})(.{3})(\d{5})(\d)(.{25})(\d{2})(\d)(\d{15})(.{40})(\d{10})(\d{15})(.{10}) {17}$/
      map:
        - bank_code
        - lot
        - lot_registry
        - movement
        - assignor_agency
        - assignor_agency_cd
        - assignor_account
        - assignor_account_cd
        - assignor_account_cd
        - our_number
        - wallet
        - doc_number
        - due
        - value
        - receiver_bank
        - receiver_agency
        - receiver_agency_cd
        - assignor_use
        - currency
        - payer_document_type
        - payer_document
        - payer_name
        - contract
        - tax
        - occurrence

    TITLE_U:
      pattern: /^(.{3})(\d{4})3(\d{5})U (\d{2})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{8})(\d{8})(.{4})(.{8})(\d{15})(.{30})(\d{3})(\d{20}) {7}$/
      map:
        - bank_code
        - lot
        - lot_registry
        - movement
        - fine_value
        - discount_value
        - rebate
        - iof
        - value_received
        - value_net
        - expenses
        - credits
        - occurrence_date
        - credit_date
        - payer_occurrence_code
        - payer_occurrence_date
        - payer_occurrence_value
        - payer_occurrence_detail
        - corresponding_bank
        - corresponding_bank_our_number

    LOT_TRAILER:
      pattern: /^(.{3})(\d{4})5 {9}(\d{6})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(.{8}) {117}$/
      map:
        - bank_code
        - lot
        - lot_registry_count
        - title_cs_count
        - title_cs_total
        - title_cv_count
        - title_cv_total
        - title_cc_count
        - title_cc_total
        - title_cd_count
        - title_cd_total
        - warning

    FILE_TRAILER:
      pattern: /^(.{3})(\d{4})9 {9}(\d{6})(\d{6})(\d{6}) {205}$/
      map:
        - bank_code
        - lot
        - lot_count
        - registry_count
        - reconciliation_accounts_count

CNAB400_BANESE:
  registry_length: 400

  structure:
    - unique: HEADER
    - multiple: TRANSACTION
    - unique: TRAILER

  registries:
    HEADER:
      pattern: /^02RETORNO(\d{2}).{15}(.{20})(.{30})(.{3})(.{15})(\d{6})(\d{2})(\d{14}) {273}(\d{5})(\d{6})$/
      map:
        - service_code
        - assignor_agency_account
        - assignor_name
        - bank_code
        - bank_name
        - record_date
        - assignor_document_type
        - assignor_document
        - file_sequence
        - registry

    TRANSACTION:
      pattern: /^1(\d{2})(\d{14})(.{20})(.{25})(\d{20}) {25}(\d)(\d{2})(\d{6})(.{10}) {20}(\d{6})(\d{13})(.{3})(\d{5})(\d{2})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13}) {9}(.)(\d{12})(\d{6})(\d{13})(\d{2})(\d{2}) {54}(\d{2})(\d)(\d{6})$/
      map:
        - assignor_document_type
        - assignor_document
        - assignor_agency_account
        - assignor_use
        - our_number
        - wallet
        - occurrence
        - occurrence_date
        - your_number
        - due
        - value
        - receiver_bank
        - receiver_agency
        - kind
        - tax
        - expenses
        - fine_discount
        - iof
        - rebate
        - discount_value
        - value_received
        - late_fine
        - credits
        - confirm_late
        - confirm_late_charge
        - confirm_discount
        - confirm_discount_value
        - confirm_instruction1
        - confirm_instruction2
        - confirm_protest
        - currency
        - registry

    TRAILER:
      pattern: /^92(\d{2})(.{3}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{8})(\d{14})(\d{8}) {10}(\d{14})(\d{3})(\d{14})(\d{14})(\d{14})(\d{14}) {144}(\d{6})$/
      map:
        - service_code
        - bank_code
        - title_cs_count
        - title_cs_total
        - warning_cs
        - title_cv_count
        - title_cv_total
        - warning_cv
        - title_cc_count
        - title_cc_total
        - warning_cc
        - title_cd_count
        - title_cd_total
        - warning_cd
        - discount_margin
        - down_rate
        - regular_titles
        - loan_limit
        - loan_balance
        - loan_fine
        - registry

CNAB400_BNB:
  registry_length: 400

  structure:
    - unique: HEADER
    - multiple: TRANSACTION
    - unique: TRAILER

  registries:
    HEADER:
      pattern: /^02RETORNO(\d{2}).{15}(\d{14}) {6}(.{30})(.{3})(.{15})(\d{6})(.{8})(\d{5}) {6}(\d{6}) {269}(\d{6})$/
      map:
        - service_code
        - assignor_agency_account
        - assignor_name
        - bank_code
        - bank_name
        - record_date
        - record_density
        - file_sequence
        - credit_date
        - registry

    TRANSACTION:
      pattern: /^1(\d{2})(\d{14})(\d{14}) {6}(.{25})(\d{8})(\d{10}) {27}(\d)(\d{2})(\d{6})(.{10})(\d{8}) {12}(\d{6})(\d{13})(.{3})(\d{4}) (\d{2})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(\d{13})(.{115})(\d{6})$/
      map:
        - assignor_document_type
        - assignor_document
        - assignor_agency_account
        - assignor_use
        - our_number
        - contract
        - wallet
        - occurrence
        - occurrence_date
        - your_number
        - confirm_our_number
        - due
        - value
        - receiver_bank
        - receiver_agency
        - kind
        - tax
        - expenses
        - fine
        - ioc
        - rebate
        - discount_value
        - value_received
        - late_fine
        - error_table
        - registry

    TRAILER:
      pattern: /^92(\d{2})(.{3}) {10}(\d{8})(\d{14})(\d{8}) {347}(\d{6})$/
      map:
        - service_code
        - bank_code
        - title_cs_count
        - title_cs_total
        - warning_cs
        - registry
