# Banese

structure:
  - FILE_HEADER
  -
    - LOT_HEADER
    -
      - TITLE_T TITLE_U
    - LOT_TRAILER
  - FILE_TRAILER

registries:
  FILE_HEADER:
    pattern: /^(047)(\d{4})0 {9}(\d)(\d{14})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{30}) {10}2(\d{8})(\d{6})(\d{6})\d{3}\d{5}(.{20})(.{20}) {29}$/
    map:
      - bank_code
      - lot
      - assignor_document_type
      - assignor_document
      - assignment_covenant
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - assignor_name
      - bank_name
      - record_date
      - record_time
      - file_sequence
      - bank_use
      - assignor_use

  LOT_HEADER:
    pattern: /^(047)(\d{4})1T(\d{2}) {2}\d{3} (\d)(\d{15})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{40})(.{40})(\d{8})(\d{8})(\d{8}) {33}$/
    map:
      - bank_code
      - lot
      - service_code
      - assignor_document_type
      - assignor_document
      - assignment_covenant
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - assignor_name
      - message1
      - message2
      - shipping_return_number
      - shipping_return_record_date
      - credit_date

  TITLE_T:
    pattern: /^(047)(\d{4})3(\d{5})T (\d{2})(\d{5})(.)(\d{12})(.)(.)(\d{19})(\d)(\d)(.{15})(\d{8})(\d{15})(\d{3})(\d{5})(\d)(.{25})(\d{2})(\d)(\d{15})(.{40})(\d{10})(\d{15})(.{10}) {17}$/
    map:
      - bank_code
      - lot
      - lot_registry
      - movement
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - our_number
      - our_number_cd
      - wallet
      - doc_number
      - due
      - value
      - receiver_bank
      - receiver_agency
      - receiver_agency_cd
      - assignor_use
      - currency
      - payer_document_type
      - payer_document
      - payer_name
      - contract
      - tax
      - occurrence

  TITLE_U:
    pattern: /^(047)(\d{4})3(\d{5})U (\d{2})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{8})(\d{8})(.{4})(.{8})(\d{15})(.{30})(\d{3})(\d{19})(\d) {7}$/
    map:
      - bank_code
      - lot
      - lot_registry
      - movement
      - fine_value
      - discount_value
      - rebate
      - ioc_iof
      - value_received
      - value_net
      - expenses
      - credits
      - occurrence_date
      - credit_date
      - payer_occurrence_code
      - payer_occurrence_date
      - payer_occurrence_value
      - payer_occurrence_detail
      - corresponding_bank
      - corresponding_bank_our_number
      - corresponding_bank_our_number_cd

  LOT_TRAILER:
    pattern: /^(047)(\d{4})5 {9}(\d{6})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(.{8}) {117}$/
    map:
      - bank_code
      - lot
      - lot_registry_count
      - cs_count
      - cs_total
      - cv_count
      - cv_total
      - cc_count
      - cc_total
      - cd_count
      - cd_total
      - warning

  FILE_TRAILER:
    pattern: /^(047)(\d{4})9 {9}(\d{6})(\d{6})(\d{6}) {205}$/
    map:
      - bank_code
      - lot
      - lot_count
      - registry_count
      - reconciliation_accounts_count

movement:
  '02': Entrada Confirmada
  '03': Entrada Rejeitada
  '04': Transferência de Carteira/Entrada
  '05': Transferência de Carteira/Baixa
  '06': Liquidação
  '07': Confirmação do Recebimento da Instrução de Desconto
  '08': Confirmação do Recebimento do Cancelamento do Desconto
  '09': Baixa
  '11': Títulos em Carteira (Em Ser)
  '12': Confirmação Recebimento Instrução de Abatimento
  '13': Confirmação Recebimento Instrução de Cancelamento Abatimento
  '14': Confirmação Recebimento Instrução Alteração de Vencimento
  '15': Franco de Pagamento
  '17': Liquidação Após Baixa ou Liquidação Título Não Registrado
  '19': Confirmação Recebimento Instrução de Protesto
  '20': Confirmação Recebimento Instrução de Sustação/Cancelamento de Protesto
  '23': Remessa a Cartório (Aponte em Cartório)
  '24': Retirada de Cartório e Manutenção em Carteira
  '25': Protestado e Baixado (Baixa por Ter Sido Protestado)
  '26': Instrução Rejeitada
  '27': Confirmação do Pedido de Alteração de Outros Dados
  '28': Débito de Tarifas/Custas
  '29': Ocorrências do Pagador
  '30': Alteração de Dados Rejeitada
  '33': Confirmação da Alteração dos Dados do Rateio de Crédito
  '34': Confirmação do Cancelamento dos Dados do Rateio de Crédito
  '35': Confirmação do Desagendamento do Débito Automático
  '36': Confirmação de envio de e-mail/SMS
  '37': Envio de e-mail/SMS rejeitado
  '38': Confirmação de alteração do Prazo Limite de Recebimento (a data deve ser informada no campo 28.3.p)
  '39': Confirmação de Dispensa de Prazo Limite de Recebimento
  '40': Confirmação da alteração do número do título dado pelo Beneficiário
  '41': Confirmação da alteração do número controle do Participante
  '42': Confirmação da alteração dos dados do Pagador
  '43': Confirmação da alteração dos dados do Sacador/Avalista
  '44': Título pago com cheque devolvido
  '45': Título pago com cheque compensado
  '46': Instrução para cancelar protesto confirmada
  '47': Instrução para protesto para fins falimentares confirmada
  '48': Confirmação de instrução de transferência de carteira/modalidade de cobrança
  '49': Alteração de contrato de cobrança
  '50': Título pago com cheque pendente de liquidação
  '51': Título DDA reconhecido pelo Pagador
  '52': Título DDA não reconhecido pelo Pagador
  '53': Título DDA recusado pela CIP
  '54': Confirmação da Instrução de Baixa de Título Negativado sem Protesto
  '55': Confirmação de Pedido de Dispensa de Multa
  '56': Confirmação do Pedido de Cobrança de Multa
  '57': Confirmação do Pedido de Alteração de Cobrança de Juros
  '58': Confirmação do Pedido de Alteração do Valor/Data de Desconto
  '59': Confirmação do Pedido de Alteração do Beneficiário do Título
  '60': Confirmação do Pedido de Dispensa de Juros de Mora
  '61': Confirmação de Alteração do Valor Nominal do Título
  '63': Título Sustado Judicialmente
  '64': Confirmação de alteração do valor mínimo/percentual
  '65': Confirmação de alteração do valor máximo/percentual

occurrence:
  A:
    '01': Código do Banco Inválido
    '02': Código do Registro Detalhe Inválido
    '03': Código do Segmento Inválido
    '04': Código de Movimento Não Permitido para Carteira
    '05': Código de Movimento Inválido
    '06': Tipo/Número de Inscrição do Beneficiário Inválidos
    '07': Agência/Conta/DV Inválido
    '08': Nosso Número Inválido
    '09': Nosso Número Duplicado
    '10': Carteira Inválida
    '11': Forma de Cadastramento do Título Inválido
    '12': Tipo de Documento Inválido
    '13': Identificação da Emissão do Boleto de Pagamento Inválida
    '14': Identificação da Distribuição do Boleto de Pagamento Inválida
    '15': Características da Cobrança Incompatíveis
    '16': Data de Vencimento Inválida
    '17': Data de Vencimento Anterior a Data de Emissão
    '18': Vencimento Fora do Prazo de Operação
    '19': Título a Cargo de Bancos Correspondentes com Vencimento Inferior a XX Dias
    '20': Valor do Título Inválido
    '21': Espécie do Título Inválida
    '22': Espécie do Título Não Permitida para a Carteira
    '23': Aceite Inválido
    '24': Data da Emissão Inválida
    '25': Data da Emissão Posterior a Data de Entrada
    '26': Código de Juros de Mora Inválido
    '27': Valor/Taxa de Juros de Mora Inválido
    '28': Código do Desconto Inválido
    '29': Valor do Desconto Maior ou Igual ao Valor do Título
    '30': Desconto a Conceder Não Confere
    '31': Concessão de Desconto - Já Existe Desconto Anterior
    '32': Valor do IOF Inválido
    '33': Valor do Abatimento Inválido
    '34': Valor do Abatimento Maior ou Igual ao Valor do Título
    '35': Valor a Conceder Não Confere
    '36': Concessão de Abatimento - Já Existe Abatimento Anterior
    '37': Código para Protesto Inválido
    '38': Prazo para Protesto Inválido
    '39': Pedido de Protesto Não Permitido para o Título
    '40': Título com Ordem de Protesto Emitida
    '41': Pedido de Cancelamento/Sustação para Títulos sem Instrução de Protesto
    '42': Código para Baixa/Devolução Inválido
    '43': Prazo para Baixa/Devolução Inválido
    '44': Código da Moeda Inválido
    '45': Nome do Pagador Não Informado
    '46': Tipo/Número de Inscrição do Pagador Inválidos
    '47': Endereço do Pagador Não Informado
    '48': CEP Inválido
    '49': CEP Sem Praça de Cobrança (Não Localizado)
    '50': CEP Referente a um Banco Correspondente
    '51': CEP incompatível com a Unidade da Federação
    '52': Unidade da Federação Inválida
    '53': Tipo/Número de Inscrição do Sacador/Avalista Inválidos
    '54': Sacador/Avalista Não Informado
    '55': Nosso número no Banco Correspondente Não Informado
    '56': Código do Banco Correspondente Não Informado
    '57': Código da Multa Inválido
    '58': Data da Multa Inválida
    '59': Valor/Percentual da Multa Inválido
    '60': Movimento para Título Não Cadastrado
    '61': Alteração da Agência Cobradora/DV Inválida
    '62': Tipo de Impressão Inválido
    '63': Entrada para Título já cadastrado
    '64': Número da Linha Inválido
    '65': Código do Banco para Débito Inválido
    '66': Agência/Conta/DV para Débito Inválido
    '67': Dados para Débito incompatível com a Identificação da Emissão do Boleto de Pagamento
    '68': Débito Automático Agendado
    '69': Débito Não Agendado - Erro nos Dados da Remessa
    '70': Débito Não Agendado - Pagador Não Consta do Cadastro de Autorizante
    '71': Débito Não Agendado - Beneficiário Não Autorizado pelo Pagador
    '72': Débito Não Agendado - Beneficiário Não Participa da Modalidade Débito Automático
    '73': Débito Não Agendado - Código de Moeda Diferente de Real (R$)
    '74': Débito Não Agendado - Data Vencimento Inválida
    '75': Débito Não Agendado, conforme seu Pedido, Título Não Registrado
    '76': Débito Não Agendado, Tipo/Num. Inscrição do Debitado, Inválido
    '77': Transferência para Desconto Não Permitida para a Carteira do Título
    '78': Data Inferior ou Igual ao Vencimento para Débito Automático
    '79': Data Juros de Mora Inválido
    '80': Data do Desconto Inválida
    '81': Tentativas de Débito Esgotadas - Baixado
    '82': Tentativas de Débito Esgotadas - Pendente
    '83': Limite Excedido
    '84': Número Autorização Inexistente
    '85': Título com Pagamento Vinculado
    '86': Seu Número Inválido
    '87': e-mail/SMS enviado
    '88': e-mail Lido
    '89': e-mail/SMS devolvido - endereço de e-mail ou número do celular incorreto
    '90': e-mail devolvido - caixa postal cheia
    '91': e-mail/número do celular do Pagador não informado
    '92': Pagador optante por Boleto de Pagamento Eletrônico - e-mail não enviado
    '93': Código para emissão de Boleto de Pagamento não permite envio de e-mail
    '94': Código da Carteira inválido para envio e-mail
    '95': Contrato não permite o envio de e-mail
    '96': Número de contrato inválido
    '97': Rejeição da alteração do prazo limite de recebimento (a data deve ser informada no campo 28.3.p)
    '98': Rejeição de dispensa de prazo limite de recebimento
    '99': Rejeição da alteração do número do título dado pelo Beneficiário
    'A1': Rejeição da alteração do número controle do participante
    'A2': Rejeição da alteração dos dados do Pagador
    'A3': Rejeição da alteração dos dados do Sacador/avalista
    'A4': Pagador DDA
    'A5': Registro Rejeitado – Título já Liquidado
    'A6': Código do Convenente Inválido ou Encerrado
    'A7': Título já se encontra na situação Pretendida
    'A8': Valor do Abatimento inválido para cancelamento
    'A9': Não autoriza pagamento parcial
    'B1': Autoriza recebimento parcial
    'B2': Valor Nominal do Título Conflitante
    'B3': Tipo de Pagamento Inválido
    'B4': Valor Máximo/Percentual Inválido
    'B5': Valor Mínimo/Percentual Inválido
    'ZY': Já existe um movimento (Inclusão/Alteração/Baixa) em processamento para esse boleto na Base Centralizada
    'ZZ': Existe mais de um tipo de movimento (Inclusão/Alteração/Baixa) para o mesmo boleto em um mesmo arquivo de remessa

  B:
    '01': Tarifa de Extrato de Posição
    '02': Tarifa de Manutenção de Título Vencido
    '03': Tarifa de Sustação
    '04': Tarifa de Protesto
    '05': Tarifa de Outras Instruções
    '06': Tarifa de Outras Ocorrências
    '07': Tarifa de Envio de Duplicata ao Pagador
    '08': Custas de Protesto
    '09': Custas de Sustação de Protesto
    '10': Custas de Cartório Distribuidor
    '11': Custas de Edital
    '12': Tarifa Sobre Devolução de Título Vencido
    '13': Tarifa Sobre Registro Cobrada na Baixa/Liquidação
    '14': Tarifa Sobre Reapresentação Automática
    '15': Tarifa Sobre Rateio de Crédito
    '16': Tarifa Sobre Informações Via Fax
    '17': Tarifa Sobre Prorrogação de Vencimento
    '18': Tarifa Sobre Alteração de Abatimento/Desconto
    '19': Tarifa Sobre Arquivo mensal (Em Ser)
    '20': Tarifa Sobre Emissão de Boleto de Pagamento Pré-Emitido pelo Banco

  C:
    '01': Por Saldo
    '02': Por Conta
    '03': Liquidação no Guichê de Caixa em Dinheiro
    '04': Compensação Eletrônica
    '05': Compensação Convencional
    '06': Por Meio Eletrônico
    '07': Após Feriado Local
    '08': Em Cartório
    '09': Comandada Banco
    '10': Comandada Cliente Arquivo
    '11': Comandada Cliente On-line
    '12': Decurso Prazo - Cliente
    '13': Decurso Prazo - Banco
    '14': Protestado
    '15': Título Excluído Valor dos Juros / Multa / Encargo
    '30': Liquidação no Guichê de Caixa em Cheque
    '31': Liquidação em banco correspondente
    '32': Liquidação Terminal de Autoatendimento
    '33': Liquidação na Internet (Home banking)
    '34': Liquidado Office Banking
    '35': Liquidado Correspondente em Dinheiro
    '36': Liquidado Correspondente em Cheque
    '37': Liquidado por meio de Central de Atendimento (Telefone)

movement_to_occurrence:
  '02': A
  '03': A
  '06': C
  '09': C
  '17': C
  '26': A
  '28': B
  '30': A
