# Banese

structure:
  - FILE_HEADER
  -
    - LOT_HEADER
    -
      - TITLE_T TITLE_U
    - LOT_TRAILER
  - FILE_TRAILER

registries:
  FILE_HEADER:
    pattern: /^(047)(\d{4})0 {9}(\d)(\d{14})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{30}) {10}2(\d{8})(\d{6})(\d{6})\d{3}\d{5}(.{20})(.{20}) {29}$/
    map:
      - bank_code
      - lot
      - assignor_document_type
      - assignor_document
      - assignment_covenant
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - assignor_name
      - bank_name
      - record_date
      - record_time
      - file_sequence
      - bank_use
      - assignor_use

  LOT_HEADER:
    pattern: /^(047)(\d{4})1T(\d{2}) {2}\d{3} (\d)(\d{15})(\d{20})(\d{5})(.)(\d{12})(.)(.)(.{30})(.{40})(.{40})(\d{8})(\d{8})(\d{8}) {33}$/
    map:
      - bank_code
      - lot
      - service_code
      - assignor_document_type
      - assignor_document
      - assignment_covenant
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - assignor_name
      - message1
      - message2
      - shipping_return_number
      - shipping_return_record_date
      - credit_date

  TITLE_T:
    pattern: /^(047)(\d{4})3(\d{5})T (\d{2})(\d{5})(.)(\d{12})(.)(.)(\d{19})(\d)(\d)(.{15})(\d{8})(\d{15})(\d{3})(\d{5})(\d)(.{25})(\d{2})(\d)(\d{15})(.{40})(\d{10})(\d{15})(.{10}) {17}$/
    map:
      - bank_code
      - lot
      - lot_registry
      - movement
      - assignment_agency
      - assignment_agency_cd
      - assignment_account
      - assignment_account_cd
      - assignment_agency_account_cd
      - our_number
      - our_number_cd
      - wallet
      - doc_number
      - due
      - value
      - receiver_bank
      - receiver_agency
      - receiver_agency_cd
      - assignor_use
      - currency
      - payer_document_type
      - payer_document
      - payer_name
      - contract
      - tax
      - occurrence

  TITLE_U:
    pattern: /^(047)(\d{4})3(\d{5})U (\d{2})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{15})(\d{8})(\d{8})(.{4})(.{8})(\d{15})(.{30})(\d{3})(\d{19})(\d) {7}$/
    map:
      - bank_code
      - lot
      - lot_registry
      - movement
      - fine_value
      - discount_value
      - rebate
      - ioc_iof
      - value_received
      - value_net
      - expenses
      - credits
      - occurrence_date
      - credit_date
      - payer_occurrence_code
      - payer_occurrence_date
      - payer_occurrence_value
      - payer_occurrence_detail
      - corresponding_bank
      - corresponding_bank_our_number
      - corresponding_bank_our_number_cd

  LOT_TRAILER:
    pattern: /^(047)(\d{4})5 {9}(\d{6})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(\d{6})(\d{17})(.{8}) {117}$/
    map:
      - bank_code
      - lot
      - lot_registry_count
      - title_cs_count
      - title_cs_total
      - title_cv_count
      - title_cv_total
      - title_cc_count
      - title_cc_total
      - title_cd_count
      - title_cd_total
      - warning

  FILE_TRAILER:
    pattern: /^(047)(\d{4})9 {9}(\d{6})(\d{6})(\d{6}) {205}$/
    map:
      - bank_code
      - lot
      - lot_count
      - registry_count
      - reconciliation_accounts_count
